name: "AutoUpdate"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Autoupdate something!
        run: |
          run: echo 'Ali Rasoulian'
          git config --global user.email "arasoulian@gmail.com"
          git config --global user.name "Ali Rasoulian"
          git add -A
          git commit -m "Automatic update"
          git push
